on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: latest
      - run: clojure -M:site
      - uses: gremid/tei-stylesheets-action@10a6f09e7e7ce2fa87ee75c868a06a9d4f3783b2
        with:
          transform: teitoodd
          source: ./basisformat_all.odd
          target: ./basisformat_all.xml
      - uses: gremid/tei-stylesheets-action@10a6f09e7e7ce2fa87ee75c868a06a9d4f3783b2
        with:
          transform: teitoodd
          source: ./basisformat_ms.odd
          target: ./basisformat_ms.xml
      - uses: gremid/tei-stylesheets-action@10a6f09e7e7ce2fa87ee75c868a06a9d4f3783b2
        with:
          transform: teitornc
          source: ./propy.odd
          target: ./public/propy.rnc
      - uses: gremid/tei-stylesheets-action@10a6f09e7e7ce2fa87ee75c868a06a9d4f3783b2
        with:
          transform: teitorelaxng
          source: ./propy.odd
          target: ./public/propy.rng
      - uses: gremid/tei-stylesheets-action@10a6f09e7e7ce2fa87ee75c868a06a9d4f3783b2
        with:
          transform: teitoschematron
          source: ./propy.odd
          target: ./public/propy.sch.xsl
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
