on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: gremid/tei-stylesheets-action@v7.54.0.1
        with:
          transform: teitoodd
          source: ./basisformat_all.odd
          target: ./basisformat_all.xml
      - uses: gremid/tei-stylesheets-action@v7.54.0.1
        with:
          transform: teitoodd
          source: ./basisformat_ms.odd
          target: ./basisformat_ms.xml
      - uses: gremid/tei-stylesheets-action@v7.54.0.1
        with:
          transform: teitornc
          source: ./propy.odd
          target: ./public/propy.rnc
      - uses: gremid/tei-stylesheets-action@v7.54.0.1
        with:
          transform: teitorelaxng
          source: ./propy.odd
          target: ./public/propy.rng
      - uses: gremid/tei-stylesheets-action@v7.54.0.1
        with:
          transform: teitoschematron
          source: ./propy.odd
          target: ./public/propy.sch.xsl
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: latest
      - run: clojure -M:site
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
